site_name: Holm-Seppensen
repo_url: https://github.com/jpfauatwork/Holm-Seppensen
repo_name: Holm-Seppensen
theme:
    name: material
    favicon: images/favicon.png
    icon:
      logo: material/map
      repo: fontawesome/brands/github
    palette:
      scheme: slate
    features:
      - navigation.sections
nav:
  - 'Einleitung': 'index.md'
  - 'Ticker': 'ticker.md'
  - 'Verkehr':
    - 'Übersicht': 'verkehr/index.md' 
    - 'ÖPNV':
      - 'Heidebahn': 'verkehr/oepnv/heidebahn.md'
      - 'Heide-Shuttle': 'verkehr/oepnv/heide-shuttle.md'
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search